# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=10000
HISTFILESIZE=20000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
shopt -s globstar

PS1='\[\033[01;32m\]\u@$NAMESPACE\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

export NAMESPACE=$(hostname)

alias k8s-secret='source k8s-secret'
alias k='kubectl'
alias kedit-secret="KUBE_EDITOR=/opt/kube-secret-editor.py kubectl edit secret"
alias kubectl-edit-secret="KUBE_EDITOR=/opt/kube-secret-editor.py kubectl edit secret"

cbold='\033[1m'
cunderline='\033[4m'
cnone='\033[0m'

if [ -d "/run/secrets/kubernetes.io/serviceaccount" ]; then
    echo -e "Kubectl configured using ${cbold}serviceaccount${cnone}."
    export NAMESPACE=$(cat /run/secrets/kubernetes.io/serviceaccount/namespace)
elif [ -f "$HOME/.kube/config" ]; then
    echo -e "Kubectl configured using ${cbold}.kube/config${cnone}."
else
    echo "Kubectl not configured. Please configure yourself before using kubectl."
fi

echo -e "Type ${cbold}toolkit-help${cnone} for available commands."
