apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: test-app

build:
  local:
    useBuildkit: true
  artifacts:
    - image: ghcr.io/brtchkv/test-repository/test-app
      docker:
        dockerfile: Dockerfile
        secrets:
          - id: MY_SECRET_1
            env: MY_SECRET_1
          - id: MY_SECRET_2
            env: MY_SECRET_2

profiles:
  - name: dev
    activation:
      - command: run