name: Test Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/skaffold-deploy.yml
    with:
      skaffold_profile: dev
      skaffold_command: run
      skaffold_extra_params: "--cache-artifacts=false"
      workdir: .
      secrets_map: |
        MY_SECRET_1=${{ secrets.MY_SECRET_1 }}                                                                                                                                           
        MY_SECRET_2=${{ secrets.MY_SECRET_2 }}
  secrets: inherit